# Generated by Django 4.1.7 on 2023-06-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='chosen_group',
            field=models.CharField(blank=True, choices=[], max_length=100, null=True),
        ),
    ]
