# Generated by Django 4.1.7 on 2023-05-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chosen_group',
            field=models.CharField(blank=True, choices=[('owner', 'owner'), ('worker', 'worker')], max_length=100, null=True),
        ),
    ]
