# Generated by Django 4.1.7 on 2023-05-21 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_name_profile_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='surname',
            new_name='username',
        ),
    ]
