# Generated by Django 4.1.7 on 2023-04-28 17:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_property_uuid_alter_property_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
