# Generated by Django 4.1.7 on 2023-05-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_rename_adress_property_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='address',
            new_name='adress',
        ),
    ]
