# Generated by Django 4.1.7 on 2023-05-09 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_rename_address_property_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='adress',
            new_name='address',
        ),
    ]
