# Generated by Django 4.1.7 on 2023-05-21 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_rename_adress_property_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='id',
            new_name='property_id',
        ),
    ]
